### PR TITLE
Fix the link from .tk site to the correct one

### PR DESCRIPTION
**Pull request by bretonium**

### CODE REVIEW

**Comment by ResamVi** [comment]
Fair enough but the site isn't running anyway though. Are you guys still playing???

**Comment by bretonium** [comment]
> Fair enough but the site isn't running anyway though.

This is another thing i wanted to ask you to fix

> Are you guys still playing???

Almost every day

**Comment by ResamVi** [comment]
OK I can make it work I just need the econ pass

**Comment by bretonium** [comment]
Could you please merge and deploy this fix?

**Comment by ResamVi** [comment]
Not sure if its deployed github image repos and my whole devops kinda scuffed here lol

just tell me if not

**Pull request merged**
